### ISSUE TITLE
Shortcuts

### ISSUE THREAD

**Issue by JochiSt** [ntim/tallysheet#11]
A button to recall the last booking would be great. This is a nice feature, which is usable, when drinking two bottles or more of water per day.

**Comment by JochiSt** [comment]
Erklärung für Tim: 
Wenn ich eine Flasche Wasser abrechne, dann muss ich umständlich immer auf New Entry meinen Namen aussuchen und dann noch ein Getränk auswählen, dann Anzahl 1 eintragen und dann auf OK.

Wenn es quasi eine Seite geben würde, wo ich mit einem Klick eine Flasche Wasser abrechnen könnte wäre das Mega.

**Comment by JochiSt** [comment]
Also eine Funktion, die die letzte Buchung wiederholt.

**Comment by ntim** [comment]
See 0d90c86f7a9016dcdb48d4dd774b094b30aa79ee

**Comment by JochiSt** [comment]
Danke, funktioniert :-)
