### ISSUE TITLE
Static flash message entry is valid but not shown

### ISSUE THREAD

**Issue by FlorianScheuch** [ntim/tallysheet#7]
A valid, not-timed-out message is not shown.

I attached the screenshots of the main page and the admin page.

The numbers of the message ids are 2, 3 and 4 (in the displayed order in the admin view)

Message 4 timed out. Message 3 was gone, too. Message 3 had to show up 1 hour more, though.

![bildschirmfoto 2016-07-15 um 14 06 57](https://cloud.githubusercontent.com/assets/5549906/16874142/f03a246e-4a97-11e6-859e-d6461b91155f.png)
![bildschirmfoto 2016-07-15 um 14 07 03](https://cloud.githubusercontent.com/assets/5549906/16874143/f087e604-4a97-11e6-86db-d3b92b98f263.png)

**Comment by ntim** [comment]
Likely a timezone issue

**Comment by ntim** [comment]
Fixed 3d2cc315de361cd151177c26af634277e374badb
